# Generated by Django 5.1.4 on 2024-12-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adrmail', models.CharField(max_length=45)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.employee')),
            ],
            options={
                'db_table': 'Email',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('filepath', models.CharField(max_length=45)),
                ('objet', models.CharField(max_length=45)),
                ('date_mail', models.DateTimeField()),
                ('message', models.TextField()),
                ('is_reply', models.BooleanField()),
                ('main_message', models.TextField()),
                ('date_main_message', models.DateTimeField()),
                ('email_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.email')),
            ],
            options={
                'db_table': 'Mail',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=10)),
                ('email_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.email')),
                ('mail_identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mail')),
            ],
            options={
                'db_table': 'Receiver',
            },
        ),
    ]
