# Generated by Django 5.1.4 on 2024-12-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_mail_filepath_alter_mail_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.employee'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email_address_id',
            field=models.ForeignKey(db_column='email_address_id', on_delete=django.db.models.deletion.CASCADE, to='base_app.email'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email_address_id',
            field=models.ForeignKey(db_column='email_address_id', on_delete=django.db.models.deletion.CASCADE, to='base_app.email'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='mail_identifiant',
            field=models.ForeignKey(db_column='mail_identifiant', on_delete=django.db.models.deletion.CASCADE, to='base_app.mail'),
        ),
    ]
