# Generated by Django 5.1.4 on 2024-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_email_employee_id_alter_mail_email_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='objet',
            field=models.CharField(max_length=300),
        ),
    ]
