# Generated by Django 5.1.4 on 2024-12-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_email_adrmail_alter_employee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
