# Generated by Django 5.1.4 on 2024-12-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_mail_mail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='adrmail',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='mail_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='objet',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='email_address_id',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='mail_identifiant',
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_email_id',
            field=models.ForeignKey(blank=True, db_column='sender_email_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.email'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='mail_id',
            field=models.ForeignKey(blank=True, db_column='mail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.mail'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email_address_id',
            field=models.ForeignKey(blank=True, db_column='email_address_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.email'),
        ),
    ]
